---

  - name: 'Instala pacotes de dependencia do sistema operacional'
    apt:
      update_cache: yes
      cache_valid_time: 3600 #1 hora
      state: latest
      name: "{{ item }}"
      state: latest
    become: yes
    with_items:
      - php
      - apache2
      - libapache2-mod-php
      - php-gd
      - mcrypt
      - php-mysql
