---

    - name: 'Update apt-get repo e cache'
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      become: yes

    - name: 'Instala pacotes de dependencia do sistema operacional'
      apt:
        name: ['mysql-server', 'python3-mysqldb']
        state: latest
      become: yes

    - name: 'Cria o banco do MySQL'
      mysql_db:
        name: "{{ wp_db_name }}"
        login_user: root
        state: present
      become: yes


    - name: 'Cria o usuário do MySQL'
      mysql_user:
        name: "{{ wp_username }}"
        password: "{{ wp_user_password }}"
        priv: "{{ wp_db_name }}.*:ALL"
        state: present
        host: '{{ item }}'
      with_items:
        - "{{ wp_webserver_ip }}"
        - "{{ wp_db_ip }}"
      become: yes


    - name: 'Configura MySQL para aceitar conexões remotas'
      copy:
       src: "files/mysqld.cnf"
       dest: '/etc/mysql/mysql.conf.d/mysqld.cnf'
      become: yes
      notify:
       - restart mysql
